const enUS = {
    'first': 'ForNet',
    'nav.network': 'Network',
    'nav.node': 'Node',
    'name': 'Name',
    'type': 'Type',
    'status': 'Status',
    'node.status.0': 'UnActive',
    'node.status.1': 'Connected',
    'node.status.2': 'Normal',
    'node.status.3': 'Forbid',
    'node.status.4': 'Delete',
    'node.type.0': 'Client',
    'node.type.1': 'Relay',
    'updatedAt': 'Updated At',
    'create': 'Create',
    'detail': 'Detail',
    'delete': 'Delete',
    'submit': 'Submit',
    'login': 'Login',
    'result.createSuccess': 'Create {0} Success.',
    'result.updateSuccess': 'Update {0} Success',
    'result.deleteSuccess': 'Delete {0} Success',
    'action.deleteConfirm': 'Are you sure to delete this {0}?',
    'invite_code': 'Invite Code',
    'active_code': 'Activation Code',
    'copy_it': 'You Have Copy It',
    'admin_token': 'Admin Token',
    'admin_token_desc': 'get from backend config',

}

export default enUS
