const zhCN = {
    'first': 'ForNet',
    'nav.network': '网络',
    'nav.node': '节点',
    'name': '名称',
    'type': '类型',
    'status': '状态',
    'node.status.0': '待激活',
    'node.status.1': '已连接',
    'node.status.2': '激活',
    'node.status.3': '禁用',
    'node.status.4': '删除',
    'node.type.0': '客户端',
    'node.type.1': '中继',
    'updatedAt': '更新时间',
    'create': '新建',
    'detail': '详情',
    'delete': '删除',
    'submit': '提交',
    'login': '登录',
    'result.createSuccess': '创建{0}成功',
    'result.updateSuccess': '更新{0}成功',
    'result.deleteSuccess': '删除{0}成功',
    'action.deleteConfirm': '您确认删除此{0}?',
    'invite_code': '邀请码',
    'active_code': '激活码',
    'copy_it': '复制成功',
    'admin_token': '管理员密钥',
    'admin_token_desc': '可从后台配置获取',
}

export default zhCN
