# name: fornet Android client build
# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         required: true
#         description: "version to release"
# jobs:
#   build_android:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           submodules: true
#       - name: Install Rust
#         uses: actions-rs/toolchain@v1        
#         with:
#           toolchain: stable
#           target: armv7-linux-androideabi, aarch64-linux-android
#           profile: minimal
#       - name: Set up JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: '17'
#           distribution: 'temurin'
#           cache: gradle
#       - name: Set up Android NDK
#         uses: nttld/setup-ndk
#         with:
#           ndk-version: 'r25b'
#           local-cache: true    
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.10.6'
#           cache: true
#       - name: Set up cargo cache
#         uses: actions/cache@v3
#         continue-on-error: false
#         with:
#           path: |
#             ~/.cargo/bin/
#             ~/.cargo/registry/index/
#             ~/.cargo/registry/cache/
#             ~/.cargo/git/db/
#             client/target/            
#           key: ubuntu-android-cargo-${{ hashFiles('**/Cargo.lock') }}
#           restore-keys: ubuntu-cargo-android
#       - name: Download Android keystore
#         id: android_keystore
#         uses: timheuer/base64-to-file@v1.0.3
#         with:
#           fileName: upload-keystore.jks
#           encodedString: ${{ secrets.KEYSTORE_BASE64 }}      
#       - name: Create key.properties
#         run: |
#           echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > app/android/sign.properties
#           echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> app/android/sign.properties
#           echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> app/android/sign.properties
#           echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> app/android/sign.properties
#       - name: Build
#         run: make release-android
#       - name: Upload artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: android-apk.zip
#           path: app/android/app/build/outputs/apk/*.apk
#           if-no-files-found: error