name: fornet Android client build
on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Rust
        uses: actions-rs/toolchain@v1        
        with:
          toolchain: stable
          target: armv7-linux-androideabi, aarch64-linux-android
          profile: minimal
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          cache: true
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            client/target/            
          key: ubuntu-android-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ubuntu-cargo-android
      - name: Build
        run: make release-android
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk.zip
          path: app/android/app/build/outputs/apk/*.apk
          if-no-files-found: error