name: fornet arm64 client build
# run at self-hosted mac min M2
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "version to release"
env:
  REGISTRY: ghcr.io
jobs:
  mac_arm64:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        settings:
          - host: self-hosted
            target: aarch64-apple-darwin
            build: make release-mac-aarch64

    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Rust
        uses: actions-rs/toolchain@v1        
        with:
          toolchain: stable
          target: ${{ matrix.settings.target }}
          profile: minimal
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            client/target/            
          key: ${{ matrix.settings.host }}-${{ matrix.settings.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ matrix.settings.host }}-cargo-${{ matrix.settings.target }}
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Build
        run: ${{ matrix.settings.build }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: release/*
          if-no-files-found: error