name: fornet arm64 client build
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "docker version to release"
env:
  REGISTRY: ghcr.io
jobs:
  docker-and-linux:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Set up Docker Buildx
        #uses: crazy-max/ghaction-setup-docker@v2
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GithubPackages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:          
          username: timzaak
          password: ${{ secrets.DOCKERHUB_BUILDJET_TOKEN }}
      -
        name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          #platforms: linux/amd64,linux/arm64
          push: true
          file: command/docker/client/client.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.REGISTRY }}/fornetcode/fornet:${{github.event.inputs.version}}
      - name: copy binary from docker to release directory
        run: |
          mkdir -p release 
          docker run --rm  -v ./release:/release ${{ env.REGISTRY }}/fornetcode/fornet:${{github.event.inputs.version}} cp /bin/fornet:/release/ && cp /bin/fornet-cli:/release          

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fornet-aarch64-unknown-linux-gnu
          path: release/*
          if-no-files-found: error