name: backend server build
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "version to release"
      branch:
        default: main
        description: "git branch"
    
env:
  REGISTRY: ghcr.io
jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.17
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'admin-web/package-lock.json'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GithubPackages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: make release-backend
      -
        name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: command/backend        
            #platforms: linux/amd64,linux/arm64
          push: true        
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: fornetcode/fornet-backend:${{github.event.inputs.version}}
